/**
 * What the app supports: one source for the in-app "What is supported" page
 * and docs/user/supported.md (generated by scripts/gen-supported-doc.ts; a
 * test fails when the doc drifts from this file).
 */
import { TEMPLATES } from '@/lib/pointing/templates'
import { CATALOGUE } from '@/lib/layout/catalogue'

export type Level = 'yes' | 'partial' | 'no'

export interface SupportRow {
  feature: string
  level: Level
  note: string
}

export interface SupportGroup {
  title: string
  rows: SupportRow[]
}

export function supportMatrix(): SupportGroup[] {
  return [
    {
      title: 'Firmware',
      rows: [
        { feature: 'ZMK keymap (.keymap)', level: 'yes', note: 'Layers, bindings, combos, layer add/rename/delete. Saves change only the edited lines; comments are kept.' },
        { feature: 'ZMK behaviors', level: 'yes', note: 'Hold-tap, mod-morph, tap-dance, macro, sticky-key and any other `zmk,behavior-*` node: edit properties, add, remove.' },
        { feature: 'ZMK #if / #ifdef inside the keymap block', level: 'partial', note: 'The keymap opens read-only so the editor never rewrites what it cannot reproduce.' },
        { feature: 'QMK VIA layout JSON', level: 'yes', note: 'Key bindings on the physical layout; combos from keymap.c when present.' },
        { feature: 'QMK keymap.c key editing', level: 'no', note: 'Edit keys through a VIA layout export instead.' },
        { feature: 'Vial / VIA live (USB) editing', level: 'no', note: 'The app edits files; it does not talk to the keyboard over USB.' },
      ],
    },
    {
      title: 'Physical layouts',
      rows: [
        { feature: 'ZMK `zmk,physical-layout` (dtsi)', level: 'yes', note: 'Detected from the shield folder.' },
        { feature: 'keymap-editor / QMK info.json, keyboard.json', level: 'yes', note: 'Detected or imported.' },
        { feature: 'keyboard-layout-editor (KLE) JSON', level: 'yes', note: 'Import file in Settings.' },
        { feature: 'Matrix transform grid', level: 'yes', note: 'Fallback when no geometry is available.' },
        { feature: 'Bundled catalogue', level: 'yes', note: `${CATALOGUE.length} layouts from ZMK's shared layouts.` },
        { feature: 'Drawing a layout by hand', level: 'no', note: 'Import a KLE file instead.' },
      ],
    },
    {
      title: 'Pointing devices',
      rows: [
        { feature: 'Tune Azoteq IQS5XX trackpad', level: 'yes', note: 'Speed, scroll, natural scroll, taps, press-and-hold, axis flips, filtering, snipe, scroll layer.' },
        { feature: 'Tune Pixart PMW3610 / PMW3360 trackball', level: 'yes', note: 'Speed, CPI, invert, smart mode, snipe, scroll layer.' },
        { feature: 'Tune Cirque Pinnacle trackpad', level: 'yes', note: 'Speed, sensitivity, invert, snipe, scroll layer.' },
        ...TEMPLATES.map((t): SupportRow => ({
          feature: `Add ${t.name.replace(/ — untested$/, '')}`,
          level: t.tested ? 'yes' : 'partial',
          note: t.tested
            ? `Tested on ${t.tested.controller}, ${t.tested.zmk}. Remove restores the files exactly.`
            : 'Untested template: review every pin in the diff preview before applying.',
        })),
        { feature: 'QMK pointing flags', level: 'yes', note: 'POINTING_DEVICE_ENABLE / DRIVER, rotation, invert, CPI in rules.mk and config.h.' },
      ],
    },
    {
      title: 'Build & flash',
      rows: [
        { feature: 'GitHub Actions firmware builds', level: 'yes', note: 'Run list and artifact download through your own `gh` login.' },
        { feature: 'Flash a UF2 to a half in bootloader', level: 'yes', note: 'Waits for the drive and copies the file.' },
        { feature: 'git commit / push from the app', level: 'no', note: 'Commit in your usual git tool; the Build tab shows uncommitted changes.' },
      ],
    },
    {
      title: 'This Mac',
      rows: [
        { feature: 'Karabiner-Elements rules', level: 'yes', note: 'Remaps, combos, layers, homerow mods for the built-in keyboard. Needs Karabiner-Elements installed.' },
        { feature: 'Scroll engine for wheel mice', level: 'yes', note: 'Reverse direction and speed. Needs Accessibility permission.' },
        { feature: 'Turn off the built-in keyboard', level: 'yes', note: 'Restored automatically if the app crashes.' },
      ],
    },
    {
      title: 'Platform',
      rows: [
        { feature: 'macOS 12+ (Apple silicon)', level: 'yes', note: 'Builds are not signed yet: macOS asks again for Documents and Accessibility access after each update.' },
        { feature: 'Automatic updates', level: 'partial', note: 'Settings › Updates checks GitHub Releases and verifies each download with the release signing key. Works once signed releases are published.' },
        { feature: 'Windows / Linux / web', level: 'no', note: 'Not in version 1.' },
      ],
    },
  ]
}

const MARK: Record<Level, string> = { yes: 'Yes', partial: 'Partly', no: 'No' }

export function supportMarkdown(): string {
  const out = ['# What Ultimate Keyboards supports', '', '<!-- generated from src/lib/supported.ts by scripts/gen-supported-doc.ts; do not edit by hand -->', '']
  for (const g of supportMatrix()) {
    out.push(`## ${g.title}`, '', '| Feature | Supported | Notes |', '|---|---|---|')
    for (const r of g.rows) out.push(`| ${r.feature} | ${MARK[r.level]} | ${r.note.replace(/\|/g, '\\|')} |`)
    out.push('')
  }
  return out.join('\n')
}

export const LEVEL_LABEL = MARK
